language: ruby
rvm: '2.5'
cache: bundler
deploy:
  provider: script
  skip_cleanup: true
  script: curl -sSL https://raw.githubusercontent.com/ManageIQ/manageiq.github.io/build/trigger.sh | bash -s
  on:
    branch: master
